class BotTexts:
    langs = {
        'ru': {
            'photoAdded': 'Фото добавлено',
            'videoAdded': 'Видео добавлено',
            'hello': 'Привет',
            'banned': 'Вы забанены',
            'sendFoto': 'Тогда отправь фото, отправлять можно сразу несколько',
            'sendVideo': 'Тогда отправь видео, отправлять можно сразу несколько',
            'subscriptionExpired': 'Время вашей подписки вышло или вы не были подписаны ранее',
            'pay_1': 'Просмотр и загрузка видео доступна только по подписке',
            'pay_2': 'Подписка оплачивается с помощью Звезд Телеграмм',
            'pay_3': 'Возврат средств за подписку не предусмотрен',
            'subСost': 'Стоимость подписки',
            'stars': 'Звезд',
            'paymentMethod': 'Отлично, выбери способ оплаты',
            'good': 'Хорошо',
            'howInAdmin': 'Как вы сюда попали?',
            'logs': 'Все в логах',
            'first_press_the_button': 'Сначала нажми на кнопку',
            'thank_you_for_purchasing_a_subscription': 'Спасибо за покупку подписки',
        },
        'en': {
            'photoAdded': 'Photo added',
            'videoAdded': 'Video added',
            'hello': 'Hello',
            'banned': 'You are banned',
            'sendFoto': 'Then send a photo',
            'sendVideo': 'Then send the video',
            'subscriptionExpired': 'Your subscription has expired or you have not subscribed before.',
            'pay_1': 'Viewing and uploading videos is only available with a subscription',
            'pay_2': 'Subscription is paid using Telegram Stars',
            'pay_3': 'There is no refund for the subscription',
            'subСost': 'Subscription cost',
            'stars': 'Stars',
            'paymentMethod': 'Great, choose a payment method',
            'good': 'Okay',
            'howInAdmin': 'How did you get here?',
            'logs': 'All in logs',
            'first_press_the_button': 'First press the button',
            'thank_you_for_purchasing_a_subscription': 'Thank you for purchasing a subscription',
        }
    }
